
-- create
CREATE TABLE EMPLOYEE (
  empId INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  address TEXT NOT NULL
);

-- insert
INSERT INTO EMPLOYEE VALUES (0001, 'Иван', 18, 'Москва');
INSERT INTO EMPLOYEE VALUES (0002, 'Петр', 22, 'Киев');
INSERT INTO EMPLOYEE VALUES (0003, 'Анна', 35, 'Минск');
INSERT INTO EMPLOYEE VALUES (0004, 'Юлия', 18, 'Астана');
INSERT INTO EMPLOYEE VALUES (0005, 'Николай', 36, 'Баку');

-- fetch 
SELECT * FROM EMPLOYEE